import { User, Product, Order, EarningsData, CMSContent } from "@/types";

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Aisha Rahman",
    email: "aisha@example.com",
    role: "user",
    isBlocked: false,
    createdAt: "2025-01-15",
    phone: "+880 1712-345678",
    address: "Dhaka, Bangladesh",
  },
  {
    id: "u2",
    name: "Fatima Ali",
    email: "fatima@example.com",
    role: "user",
    isBlocked: false,
    createdAt: "2025-02-10",
    phone: "+880 1898-765432",
    address: "Chittagong, Bangladesh",
  },
  {
    id: "u3",
    name: "Zainab Khan",
    email: "zainab@example.com",
    role: "user",
    isBlocked: true,
    createdAt: "2025-03-05",
    phone: "+880 1534-567890",
    address: "Sylhet, Bangladesh",
  },
  {
    id: "u4",
    name: "Maryam Hossain",
    email: "maryam@example.com",
    role: "user",
    isBlocked: false,
    createdAt: "2025-03-20",
    phone: "+880 1645-234567",
    address: "Rajshahi, Bangladesh",
  },
  {
    id: "u5",
    name: "Khadija Islam",
    email: "khadija@example.com",
    role: "user",
    isBlocked: false,
    createdAt: "2025-04-01",
    phone: "+880 1756-890123",
    address: "Khulna, Bangladesh",
  },
  {
    id: "u6",
    name: "Sumaiya Begum",
    email: "sumaiya@example.com",
    role: "user",
    isBlocked: false,
    createdAt: "2025-04-12",
    phone: "+880 1867-456789",
    address: "Comilla, Bangladesh",
  },
  {
    id: "u7",
    name: "Nusrat Jahan",
    email: "nusrat@example.com",
    role: "user",
    isBlocked: true,
    createdAt: "2025-05-08",
    phone: "+880 1978-012345",
    address: "Barisal, Bangladesh",
  },
  {
    id: "u8",
    name: "Taslima Akter",
    email: "taslima@example.com",
    role: "user",
    isBlocked: false,
    createdAt: "2025-05-18",
    phone: "+880 1589-678901",
    address: "Gazipur, Bangladesh",
  },
  {
    id: "u9",
    name: "Rabeya Sultana",
    email: "rabeya@example.com",
    role: "user",
    isBlocked: false,
    createdAt: "2025-06-02",
    phone: "+880 1690-123456",
    address: "Narayanganj, Bangladesh",
  },
  {
    id: "u10",
    name: "Halima Parvin",
    email: "halima@example.com",
    role: "user",
    isBlocked: false,
    createdAt: "2025-06-15",
    phone: "+880 1801-789012",
    address: "Dhaka, Bangladesh",
  },
];

export const mockAdmins: User[] = [
  {
    id: "a1",
    name: "Admin User",
    email: "admin@modestcollection.com",
    role: "super_admin",
    isBlocked: false,
    createdAt: "2024-01-01",
    phone: "+880 1700-000001",
  },
  {
    id: "a2",
    name: "Sarah Manager",
    email: "sarah@modestcollection.com",
    role: "admin",
    isBlocked: false,
    createdAt: "2024-06-15",
    phone: "+880 1700-000002",
  },
  {
    id: "a3",
    name: "Omar Editor",
    email: "omar@modestcollection.com",
    role: "admin",
    isBlocked: false,
    createdAt: "2025-01-10",
    phone: "+880 1700-000003",
  },
];

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Elegant Black Borkha",
    price: 2999,
    category: "Borkha",
    images: ["/placeholder-product.svg"],
    stock: 45,
    description: "Premium quality black borkha with intricate embroidery work.",
    status: "active",
    createdAt: "2025-01-20",
  },
  {
    id: "p2",
    name: "Premium Navy Abaya",
    price: 3499,
    category: "Abaya",
    images: ["/placeholder-product.svg"],
    stock: 30,
    description: "Luxurious navy abaya made from high-quality fabric.",
    status: "active",
    createdAt: "2025-02-05",
  },
  {
    id: "p3",
    name: "Silk Hijab - Rose Gold",
    price: 599,
    category: "Hijab",
    images: ["/placeholder-product.svg"],
    stock: 120,
    description: "Soft silk hijab in beautiful rose gold color.",
    status: "active",
    createdAt: "2025-02-15",
  },
  {
    id: "p4",
    name: "Cotton Innercap - White",
    price: 349,
    category: "Innercap",
    images: ["/placeholder-product.svg"],
    stock: 80,
    description: "Comfortable cotton innercap for daily wear.",
    status: "active",
    createdAt: "2025-03-01",
  },
  {
    id: "p5",
    name: "Embroidered Borkha - Maroon",
    price: 4499,
    category: "Borkha",
    images: ["/placeholder-product.svg"],
    stock: 15,
    description: "Heavily embroidered maroon borkha for special occasions.",
    status: "active",
    createdAt: "2025-03-10",
  },
  {
    id: "p6",
    name: "Jersey Hijab - Black",
    price: 449,
    category: "Hijab",
    images: ["/placeholder-product.svg"],
    stock: 200,
    description: "Stretchy jersey hijab, perfect for everyday use.",
    status: "active",
    createdAt: "2025-03-18",
  },
  {
    id: "p7",
    name: "Open Abaya - Dusty Pink",
    price: 3999,
    category: "Abaya",
    images: ["/placeholder-product.svg"],
    stock: 25,
    description: "Elegant open-front abaya in dusty pink shade.",
    status: "active",
    createdAt: "2025-04-02",
  },
  {
    id: "p8",
    name: "Innercap with Lace Trim",
    price: 399,
    category: "Innercap",
    images: ["/placeholder-product.svg"],
    stock: 60,
    description: "Innercap with delicate lace trim detailing.",
    status: "draft",
    createdAt: "2025-04-15",
  },
  {
    id: "p9",
    name: "Chiffon Hijab - Emerald",
    price: 549,
    category: "Hijab",
    images: ["/placeholder-product.svg"],
    stock: 0,
    description: "Lightweight chiffon hijab in emerald green.",
    status: "archived",
    createdAt: "2025-04-20",
  },
  {
    id: "p10",
    name: "Prayer Borkha - Grey",
    price: 1999,
    category: "Borkha",
    images: ["/placeholder-product.svg"],
    stock: 50,
    description: "Simple and comfortable prayer borkha in grey.",
    status: "active",
    createdAt: "2025-05-01",
  },
];

export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    userId: "u1",
    userName: "Aisha Rahman",
    items: [
      { productId: "p1", productName: "Elegant Black Borkha", quantity: 1, price: 2999 },
      { productId: "p3", productName: "Silk Hijab - Rose Gold", quantity: 2, price: 599 },
    ],
    total: 4197,
    status: "delivered",
    paymentMethod: "bKash",
    shippingAddress: "House 12, Road 5, Dhanmondi, Dhaka",
    createdAt: "2025-03-10",
  },
  {
    id: "ORD-002",
    userId: "u2",
    userName: "Fatima Ali",
    items: [
      { productId: "p2", productName: "Premium Navy Abaya", quantity: 1, price: 3499 },
    ],
    total: 3499,
    status: "shipped",
    paymentMethod: "Nagad",
    shippingAddress: "Block C, Road 7, Chittagong",
    createdAt: "2025-04-05",
  },
  {
    id: "ORD-003",
    userId: "u4",
    userName: "Maryam Hossain",
    items: [
      { productId: "p5", productName: "Embroidered Borkha - Maroon", quantity: 1, price: 4499 },
      { productId: "p4", productName: "Cotton Innercap - White", quantity: 3, price: 349 },
    ],
    total: 5546,
    status: "processing",
    paymentMethod: "Card",
    shippingAddress: "Road 12, Rajshahi",
    createdAt: "2025-05-12",
  },
  {
    id: "ORD-004",
    userId: "u5",
    userName: "Khadija Islam",
    items: [
      { productId: "p6", productName: "Jersey Hijab - Black", quantity: 5, price: 449 },
    ],
    total: 2245,
    status: "pending",
    paymentMethod: "Cash on Delivery",
    shippingAddress: "Main Road, Khulna",
    createdAt: "2025-05-20",
  },
  {
    id: "ORD-005",
    userId: "u6",
    userName: "Sumaiya Begum",
    items: [
      { productId: "p7", productName: "Open Abaya - Dusty Pink", quantity: 1, price: 3999 },
      { productId: "p3", productName: "Silk Hijab - Rose Gold", quantity: 1, price: 599 },
    ],
    total: 4598,
    status: "pending",
    paymentMethod: "bKash",
    shippingAddress: "Station Road, Comilla",
    createdAt: "2025-05-25",
  },
  {
    id: "ORD-006",
    userId: "u8",
    userName: "Taslima Akter",
    items: [
      { productId: "p10", productName: "Prayer Borkha - Grey", quantity: 2, price: 1999 },
    ],
    total: 3998,
    status: "shipped",
    paymentMethod: "Nagad",
    shippingAddress: "Gazipur Sadar, Gazipur",
    createdAt: "2025-06-01",
  },
  {
    id: "ORD-007",
    userId: "u9",
    userName: "Rabeya Sultana",
    items: [
      { productId: "p1", productName: "Elegant Black Borkha", quantity: 1, price: 2999 },
    ],
    total: 2999,
    status: "cancelled",
    paymentMethod: "Card",
    shippingAddress: "Narayanganj Sadar",
    createdAt: "2025-06-05",
  },
  {
    id: "ORD-008",
    userId: "u10",
    userName: "Halima Parvin",
    items: [
      { productId: "p2", productName: "Premium Navy Abaya", quantity: 1, price: 3499 },
      { productId: "p6", productName: "Jersey Hijab - Black", quantity: 3, price: 449 },
    ],
    total: 4846,
    status: "delivered",
    paymentMethod: "bKash",
    shippingAddress: "Mirpur, Dhaka",
    createdAt: "2025-06-10",
  },
];

export const mockEarnings: EarningsData[] = [
  { date: "Jan", revenue: 45000, orders: 32 },
  { date: "Feb", revenue: 52000, orders: 38 },
  { date: "Mar", revenue: 61000, orders: 45 },
  { date: "Apr", revenue: 48000, orders: 35 },
  { date: "May", revenue: 72000, orders: 52 },
  { date: "Jun", revenue: 68000, orders: 48 },
  { date: "Jul", revenue: 85000, orders: 62 },
  { date: "Aug", revenue: 79000, orders: 58 },
  { date: "Sep", revenue: 91000, orders: 67 },
  { date: "Oct", revenue: 95000, orders: 70 },
  { date: "Nov", revenue: 110000, orders: 82 },
  { date: "Dec", revenue: 125000, orders: 95 },
];

export const mockDailyEarnings: EarningsData[] = [
  { date: "1 Jun", revenue: 3200, orders: 4 },
  { date: "2 Jun", revenue: 4500, orders: 6 },
  { date: "3 Jun", revenue: 2800, orders: 3 },
  { date: "4 Jun", revenue: 5100, orders: 7 },
  { date: "5 Jun", revenue: 3900, orders: 5 },
  { date: "6 Jun", revenue: 4200, orders: 5 },
  { date: "7 Jun", revenue: 3600, orders: 4 },
  { date: "8 Jun", revenue: 4800, orders: 6 },
  { date: "9 Jun", revenue: 5500, orders: 8 },
  { date: "10 Jun", revenue: 4100, orders: 5 },
  { date: "11 Jun", revenue: 3700, orders: 4 },
  { date: "12 Jun", revenue: 5200, orders: 7 },
  { date: "13 Jun", revenue: 4600, orders: 6 },
  { date: "14 Jun", revenue: 3800, orders: 4 },
];

export const mockCMSContent: CMSContent[] = [
  {
    id: "cms1",
    type: "privacy_policy",
    title: "Privacy Policy",
    content:
      "At Modest Collection, we are committed to protecting your privacy. We collect personal information such as your name, email, shipping address, and payment details solely for the purpose of processing your orders and improving your shopping experience. We do not share your information with third parties except as required to fulfill your orders (e.g., shipping partners). You have the right to access, correct, or delete your personal data at any time by contacting our support team. We use cookies to enhance your browsing experience and analyze site traffic. By using our website, you consent to our privacy practices as described in this policy.",
    updatedAt: "2025-06-01",
  },
  {
    id: "cms2",
    type: "terms_conditions",
    title: "Terms & Conditions",
    content:
      "By accessing and using Modest Collection's website, you agree to be bound by these Terms & Conditions. All products are subject to availability. Prices may change without notice. We accept returns within 7 days of delivery for unused items with original packaging. Refunds are processed within 5-7 business days. We are not responsible for delays caused by shipping carriers. Unauthorized use of our website or its content is prohibited. We reserve the right to modify these terms at any time. Your continued use of the site constitutes acceptance of any changes.",
    updatedAt: "2025-06-01",
  },
  {
    id: "cms3",
    type: "contact_info",
    title: "Contact Information",
    content:
      "Modest Collection\nEmail: support@modestcollection.com\nPhone: +880 1700-000001\nAddress: House 45, Road 12, Dhanmondi, Dhaka 1205, Bangladesh\nBusiness Hours: Saturday - Thursday, 10:00 AM - 8:00 PM (BST)\nFacebook: facebook.com/modestcollection\nInstagram: instagram.com/modestcollection",
    updatedAt: "2025-06-01",
  },
];
